version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3169:4000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - app-network

  landing:
    build: ./landing/landingPage
    ports:
      - "3215:3000"
    volumes:
      - ./landing/landingPage/src:/app/src
      - /app/node_modules
    networks:
      - app-network

  dashboard:
    build: ./dashboard
    ports:
      - "4040:3001"
    volumes:
      - ./dashboard/src:/app/src
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
